### ISSUE TITLE
Teleportation Delay Behaves Unpredictably

### ISSUE THREAD

**Issue by MrCreeps** [northwesttrees-gaming/PortalGates#5]
So I just downloaded the new 1.1.0 version from CurseForge and when trying out the new teleportation countdown, it automatically teleports me, and then does the countdown.  Sometimes it will wait for the countdown to finish and then teleport, but will display the countdown, again.

[Video](https://youtu.be/Px1NKcQqoak)

(I tested it multiple times and it happened multiple times in a row)

Edit: I'm testing it more and it works if the portal gate is connected both ways. The countdown also happens on unlinked portal gates.

**Comment by northwesttreesgaming** [comment]
The video really helps, I did not noticed the first part with the countdown I think this part can be fixed for sure most likely just needs a catch to fix that.

The portal delay part where it's happening on the other portal instead might need a logic variable applied to the timing system to fix the issue. I will work on a small patch for 1.1.1, I will have to also apply the patch to 1.2.0 but most likely it's an easy fix.

Thanks for letting me know MrCreeps <3

**Comment by northwesttreesgaming** [comment]
change of plans will be in 1.2.0, there is actually a lot of stuff I need to fix in the code and it will be a bit much to do in both 1.2.0 and 1.1.1 so it will be in 1.2.0.

**Comment by northwesttreesgaming** [comment]
I fixed both issues in 1.2.0 just now so portals should now work properly once the update is released.
