### ISSUE TITLE
Obsidan Anchors Dropping from All Stone Blocks

### ISSUE THREAD

**Issue by AuraTheWise** [northwesttrees-gaming/PortalGates#6]
### Issue description

So we just updated to the new version of PortalGates and now anytime we mine stone, it seems an obsidian anchor drops along with the stone. It is simply Vanilla Stone, we dont have anything that messes with stone so i highly doubt its any other mods.

### Steps to reproduce this issue.

Make World
Mine Stone

### Minecraft and nod builds

1.19.2
PortalGates 1.6.1

### Installed modifications

![image](https://user-images.githubusercontent.com/92907171/202021856-a0532c9f-2d9e-46dd-ac57-8426f0b4123e.png)
![image](https://user-images.githubusercontent.com/92907171/202021935-b84c6c79-4b05-433a-ac43-62aa1e2e49b6.png)

**Comment by AuraTheWise** [comment]
So Further Testing shows that ANY Vanilla Stone type blocks drop obsidian Anchors, and most other blocks drop obsidian, this behaviour specifically happens only when you use the correct tool for the block. So far it has happened with Stone, All forms of Deepslate, Lecterns, Dirt, Sand, Gravel. It doesnt seem to affect blocks that dont have a specific tool

**Comment by AuraTheWise** [comment]
Issue Occurred on both 1.6.0 and 1.6.1, downgrading back to 1.5.0 fixed the issue

**Comment by northwesttreesgaming** [comment]
Thanks for the report I will look into it right now.

**Comment by northwesttreesgaming** [comment]
Found the issue I will release a patch shortly.

**Comment by northwesttreesgaming** [comment]
Curse forge might take a couple of moments to approve it, it normally does but if you need it right now its also released on MCreator.net
